### ISSUE TITLE
Console.Clear issue

### ISSUE THREAD

**Issue by brandonshawfhl** [brandonshawfhl/Quiz-Maker#16]
I am experiencing a problem with Console.Clear where it is only clearing the visible screen and not the entire console. (I'm not 100% sure I'm saying it right, but this is how I've interpreted the problem. It is the Console.Clear on line 52 of Program.

**Comment by incredibleLeitman** [comment]
Not sure if I fully understand the problem, but what Console.Clear actually does is just "scrolling" the console text so that new Console.WriteLines start in the first line. Depending on what IDE or tools you are using, the text previously printed to the console might still be visible.

Maybe you can share some screenshots or even a video to describe what you experience?
Or also show us in a live call :D
